language: cpp
matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
        - qt
        - cmake
        - fftw
        - sound-touch
        - libogg
        - libvorbis
        update: true
    script:
      - mkdir ./build
      - cd ./build
      - mkdir installs
      - export QMAKE=/usr/local/bin/qmake;
      - export PATH=/usr/local/opt/qt5/bin:$PATH;
      - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installs ../
      - make
      - make install
      - make deploy
      - make dmg
